### ISSUE TITLE
二级域名怎么cname

### ISSUE THREAD

**Issue by yukerui** [xiaokuqwq/ipcf.tk#1]
请问下，二级域名是在哪里cname啊

**Comment by yukerui** [comment]
是不是仅仅针对没有接入cf的，如果我的域名接入cf了，是不是就不能用了

**Comment by xiaokuqwq** [comment]
> 是不是针对没有访问cf的，我的域名访问cf了是不是就不能用了

是针对接入cf的域名

**Comment by xiaokuqwq** [comment]
> 下一个域名是在哪里cname啊请

如果不会saas，请看[saas教程](https://blog.xypt.ltd/archives/cfsaas.html)

**Comment by xiaokuqwq** [comment]
已解决
